CREATE ROLE shopuser WITH LOGIN PASSWORD '';
CREATE DATABASE shopdb OWNER shopuser;

\c shopdb
GRANT ALL ON SCHEMA public TO shopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO shopuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO shopuser;

\q